version: '3.8'
services:
  backend:
    build:
      context: ./chat-backend
    ports:
      - "5000:5000"
    env_file:
      - ./chat-backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatapp
    depends_on:
      - mongo

  frontend:
    build:
      context: ./chat-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
